<a href="https://colab.research.google.com/github/2303a51706/23CSBTB27-28/blob/main/Array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
List = {1:"greek1",2:'Greeks','For':3,'Greeks':6}
print("\nList with the use of mixed value:")
print(List)
print(type(List))


List with the use of mixed value:
{1: 'greek1', 2: 'Greeks', 'For': 3, 'Greeks': 6}
<class 'dict'>


In [5]:

list={1,5,2,6,7}
list1=[3,6,1,8]
print(list)
print(list1)
print(type(list))
print(type(list1))

{1, 2, 5, 6, 7}
[3, 6, 1, 8]
<class 'set'>
<class 'list'>


In [6]:
List1=["Greeks","For","Greeks"]
List2="my first lab"
List3=4.3
List4=2j+6
List5='my first lab'
print(type(List2))
print(type(List3))
print(type(List4))
print(type(List5))
print("\nList Items: ")
print(List1)
print(type(List1))
print(List1[0])
print(List1[2])

<class 'str'>
<class 'float'>
<class 'complex'>
<class 'str'>

List Items: 
['Greeks', 'For', 'Greeks']
<class 'list'>
Greeks
Greeks


In [10]:
import numpy as np
arry=np.array([[2,5],[4,2]])
arry1=np.array([[2,5,4,2],[4,2,1,0]])
arry2=np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)


[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [13]:
import numpy as np
arry1=np.array([1,3,4,5,6])
arry2=np.array([2,6,3,4,8])
print(arry1)
print(np.add(arry1,arry2))
print(np.multiply(arry1,arry2))
print(np.subtract(arry2,arry1))
print(np.divide(arry2,arry1))

print(type(arry1))



[1 3 4 5 6]
[ 3  9  7  9 14]
[ 2 18 12 20 48]
[ 1  3 -1 -1  2]
[2.         2.         0.75       0.8        1.33333333]
<class 'numpy.ndarray'>
